// pages/BaselReportPage.tsx
import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { Printer, ArrowLeft } from "lucide-react";
import { explainService } from "@/services/explainService";
import { Button } from "@/components/shared/Button";
import { LoadingState, ErrorState } from "@/components/shared/States";
import { RiskBadge } from "@/components/shared/RiskBadge";
import type { ExplanationOut } from "@/types/api";

export function BaselReportPage() {
  const { transactionId } = useParams<{ transactionId: string }>();
  const navigate = useNavigate();
  const [report, setReport] = useState<ExplanationOut | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!transactionId) return;
    setIsLoading(true);
    explainService
      .getBaselNarrative(Number(transactionId))
      .then(setReport)
      .catch(() => setError("Could not generate the Basel III audit narrative for this transaction."))
      .finally(() => setIsLoading(false));
  }, [transactionId]);

  if (isLoading) return <LoadingState label="Generating audit narrative..." />;
  if (error) return <ErrorState description={error} />;
  if (!report) return null;

  const topFraudDriver = report.top_features.find((f) => f.direction === "toward_fraud");

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <div className="flex items-center justify-between print:hidden">
        <button
          onClick={() => navigate("/portal/explainability")}
          className="flex items-center gap-1.5 text-sm text-gray-500 hover:text-[#111111]"
        >
          <ArrowLeft className="h-4 w-4" />
          Back
        </button>
        <Button variant="secondary" size="sm" onClick={() => window.print()}>
          <Printer className="h-3.5 w-3.5" />
          Print / Export PDF
        </Button>
      </div>

      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        className="rounded-2xl border border-gray-200 bg-white p-10 shadow-sm print:border-none print:shadow-none"
      >
        <div className="mb-8 border-b border-gray-100 pb-6">
          <p className="text-xs uppercase tracking-widest text-gray-400">Audit Narrative</p>
          <h1 className="font-display mt-1 text-2xl font-semibold text-[#111111]">
            Transaction #{report.transaction_id}
          </h1>
          <p className="mt-1 text-xs text-gray-400">
            Generated {new Date(report.created_at).toLocaleString()}
          </p>
        </div>

        <section className="mb-8">
          <h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-gray-400">
            Executive Summary
          </h2>
          <div className="flex items-center gap-3">
            <RiskBadge probability={topFraudDriver ? Math.abs(topFraudDriver.shap_value) : 0.5} />
          </div>
          <p className="mt-3 whitespace-pre-line text-sm leading-relaxed text-gray-700">
            {report.llm_narrative}
          </p>
        </section>

        <section className="mb-8">
          <h2 className="mb-3 text-xs font-semibold uppercase tracking-wide text-gray-400">
            Risk Analysis — Contributing Factors
          </h2>
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-100 text-left text-xs text-gray-400">
                <th className="pb-2 font-medium">Feature</th>
                <th className="pb-2 font-medium">Observed Value</th>
                <th className="pb-2 font-medium">SHAP Contribution</th>
                <th className="pb-2 font-medium">Effect</th>
              </tr>
            </thead>
            <tbody>
              {report.top_features.map((f) => (
                <tr key={f.feature} className="border-b border-gray-50">
                  <td className="py-2 font-medium text-[#111111]">{f.feature}</td>
                  <td className="py-2 text-gray-600">{f.feature_value.toFixed(3)}</td>
                  <td className="py-2 text-gray-600">{f.shap_value.toFixed(3)}</td>
                  <td className={`py-2 ${f.direction === "toward_fraud" ? "text-red-600" : "text-green-600"}`}>
                    {f.direction === "toward_fraud" ? "Elevates risk" : "Reduces risk"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        <section className="mb-8">
          <h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-gray-400">
            Compliance Assessment
          </h2>
          <p className="text-sm leading-relaxed text-gray-600">
            This narrative was generated by the FedXplain fraud detection system using SHAP
            feature attribution and LLM-based reasoning, per the model version recorded below.
            This report is intended to support — not replace — human compliance review.
          </p>
        </section>

        <section className="border-t border-gray-100 pt-6">
          <h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-gray-400">
            Audit Metadata
          </h2>
          <div className="grid grid-cols-2 gap-2 text-xs text-gray-500">
            <span>Transaction ID</span>
            <span className="text-right text-[#111111]">#{report.transaction_id}</span>
            <span>Report Generated</span>
            <span className="text-right text-[#111111]">{new Date(report.created_at).toLocaleString()}</span>
          </div>
        </section>
      </motion.div>
    </div>
  );
}
